### PR TITLE
Fix live validation for segments in the Run Editor

### LINKED ISSUE #8: Live Validation is broken for the Segments
Submitting every valid intermediate state causes the fixing algorithms to run on those intermediate states, which often causes the Best Segment Times and the following segments to get fixed in an unintended way.

### LINKED ISSUE #55: Best Segment Time incorrect when inserting splits via Editor
LiveSplit/livesplit-core#63

### PR DESCRIPTION
**Pull request by wooferzfg**
Changes to times are now submitted in `onBlur` instead of `onChange`.

Fix #8 
Fix #55

### CODE REVIEW

File: src/ui/RunEditor.tsx [hunk 1]
```diff
@@ -1510,116 +1510,116 @@ export class RunEditor extends React.Component<Props, State> {
...
+
         this.setState({
             ...this.state,
             editor: this.props.editor.stateAsJson(),
             rowState: {
                 ...this.state.rowState,
-                splitTimeIsValid: true,
-            },
+                splitTimeChanged: false
+            }
```
Comment (CryZe) [inline src/ui/RunEditor.tsx]: I'd like to keep the trailing commas in general. Just letting you know, it's not something you need to fix.
